description: 'A Streamlit application makes it easy to transform your analysis into
  an interactive dashboard using Python so users can ask and answer questions in real-time,
  without having to touch any code.'
tags:
- jump-start
- python
- streamlit
- all
title: Top 5% income share
